// -------------------------------------------------------------
//
// Module: HB_2_pl
//
// Generated by MATLAB(R) 7.2 and the Filter Design HDL Coder 1.4.
//
// Generated on: 2007-02-09 13:05:50
//
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetLanguage: Verilog
// Name: HB_2_pl
// TargetDirectory: C:\Data\QS\QuickSilver\trunk\QS1R_AB_QUARTUS\CIC
// OptimizeForHDL: On
// FIRAdderStyle: tree
// SerialPartition: -1
// AddPipelineRegisters: On
// InlineConfigurations: Off
// SafeZeroConcat: Off
// TestBenchStimulus: step ramp chirp noise 
//
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure   : Direct-Form FIR Polyphase Decimator
// Decimation Factor  : 2
// Polyphase Length   : 13
// Filter Length      : 25
// Stable             : Yes
// Linear Phase       : Yes (Type 1)
//
// Arithmetic         : fixed
// Numerator          : s19,18 -> [-1 1)
// Input              : s24,-30 -> [-9.007199e+015 9.007199e+015)
// Filter Internals   : Full Precision
//   Output           : s43,-12 -> [-1.801440e+016 1.801440e+016)  (auto determined)
//   Product          : s41,-12 -> [-4.503600e+015 4.503600e+015)  (auto determined)
//   Accumulator      : s43,-12 -> [-1.801440e+016 1.801440e+016)  (auto determined)
//   Round Mode       : No rounding
//   Overflow Mode    : No overflow
//
// Implementation Cost
// Number of Multipliers : 13
// Number of Adders      : 12
// Number of States      : 22
// MultPerInputSample    : 6.5
// AddPerInputSample     : 6
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HB_2_pl 
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [23:0] filter_in; //sfix24_E30
  output  signed [42:0] filter_out; //sfix43_E12
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: HB_2_pl
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [18:0] coeffphase1_1 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_2 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_3 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_4 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_5 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_6 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_7 = 19'b0100000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_8 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_9 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_10 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_11 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_12 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase1_13 = 19'b0000000000000000000; //sfix19_En18
  parameter signed [18:0] coeffphase2_1 = 19'b1111111111111010000; //sfix19_En18
  parameter signed [18:0] coeffphase2_2 = 19'b0000000000110110110; //sfix19_En18
  parameter signed [18:0] coeffphase2_3 = 19'b1111111011111001100; //sfix19_En18
  parameter signed [18:0] coeffphase2_4 = 19'b0000001101111001100; //sfix19_En18
  parameter signed [18:0] coeffphase2_5 = 19'b1111010111101111111; //sfix19_En18
  parameter signed [18:0] coeffphase2_6 = 19'b0010011101101100010; //sfix19_En18
  parameter signed [18:0] coeffphase2_7 = 19'b0010011101101100010; //sfix19_En18
  parameter signed [18:0] coeffphase2_8 = 19'b1111010111101111111; //sfix19_En18
  parameter signed [18:0] coeffphase2_9 = 19'b0000001101111001100; //sfix19_En18
  parameter signed [18:0] coeffphase2_10 = 19'b1111111011111001100; //sfix19_En18
  parameter signed [18:0] coeffphase2_11 = 19'b0000000000110110110; //sfix19_En18
  parameter signed [18:0] coeffphase2_12 = 19'b1111111111111010000; //sfix19_En18
  parameter signed [18:0] coeffphase2_13 = 19'b0000000000000000000; //sfix19_En18
  // Signals
  reg  [1:0] ring_count; // ufix2
  wire phase_0; // boolean
  wire phase_1; // boolean
  reg  ce_out_reg; // boolean
  reg  signed [23:0] input_register; // sfix24_E30
  reg  signed [23:0] input_pipeline_phase0 [0:5] ; // sfix24_E30
  reg  signed [23:0] input_pipeline_phase1 [0:11] ; // sfix24_E30
  wire signed [40:0] product_phase0_7; // sfix41_E12
  wire signed [40:0] product_phase1_1; // sfix41_E12
  wire signed [42:0] mul_temp; // sfix43_E12
  wire signed [40:0] product_phase1_2; // sfix41_E12
  wire signed [42:0] mul_temp_1; // sfix43_E12
  wire signed [40:0] product_phase1_3; // sfix41_E12
  wire signed [42:0] mul_temp_2; // sfix43_E12
  wire signed [40:0] product_phase1_4; // sfix41_E12
  wire signed [42:0] mul_temp_3; // sfix43_E12
  wire signed [40:0] product_phase1_5; // sfix41_E12
  wire signed [42:0] mul_temp_4; // sfix43_E12
  wire signed [40:0] product_phase1_6; // sfix41_E12
  wire signed [42:0] mul_temp_5; // sfix43_E12
  wire signed [40:0] product_phase1_7; // sfix41_E12
  wire signed [42:0] mul_temp_6; // sfix43_E12
  wire signed [40:0] product_phase1_8; // sfix41_E12
  wire signed [42:0] mul_temp_7; // sfix43_E12
  wire signed [40:0] product_phase1_9; // sfix41_E12
  wire signed [42:0] mul_temp_8; // sfix43_E12
  wire signed [40:0] product_phase1_10; // sfix41_E12
  wire signed [42:0] mul_temp_9; // sfix43_E12
  wire signed [40:0] product_phase1_11; // sfix41_E12
  wire signed [42:0] mul_temp_10; // sfix43_E12
  wire signed [40:0] product_phase1_12; // sfix41_E12
  wire signed [42:0] mul_temp_11; // sfix43_E12
  reg  signed [40:0] product_pipeline_phase0_7; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_1; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_2; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_3; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_4; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_5; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_6; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_7; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_8; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_9; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_10; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_11; // sfix41_E12
  reg  signed [40:0] product_pipeline_phase1_12; // sfix41_E12
  wire signed [42:0] sumvector1 [0:6] ; // sfix43_E12
  wire signed [40:0] add_signext; // sfix41_E12
  wire signed [40:0] add_signext_1; // sfix41_E12
  wire signed [41:0] add_temp; // sfix42_E12
  wire signed [40:0] add_signext_2; // sfix41_E12
  wire signed [40:0] add_signext_3; // sfix41_E12
  wire signed [41:0] add_temp_1; // sfix42_E12
  wire signed [40:0] add_signext_4; // sfix41_E12
  wire signed [40:0] add_signext_5; // sfix41_E12
  wire signed [41:0] add_temp_2; // sfix42_E12
  wire signed [40:0] add_signext_6; // sfix41_E12
  wire signed [40:0] add_signext_7; // sfix41_E12
  wire signed [41:0] add_temp_3; // sfix42_E12
  wire signed [40:0] add_signext_8; // sfix41_E12
  wire signed [40:0] add_signext_9; // sfix41_E12
  wire signed [41:0] add_temp_4; // sfix42_E12
  wire signed [40:0] add_signext_10; // sfix41_E12
  wire signed [40:0] add_signext_11; // sfix41_E12
  wire signed [41:0] add_temp_5; // sfix42_E12
  reg  signed [42:0] sumdelay_pipeline1 [0:6] ; // sfix43_E12
  wire signed [42:0] sumvector2 [0:3] ; // sfix43_E12
  wire signed [42:0] add_signext_12; // sfix43_E12
  wire signed [42:0] add_signext_13; // sfix43_E12
  wire signed [43:0] add_temp_6; // sfix44_E12
  wire signed [42:0] add_signext_14; // sfix43_E12
  wire signed [42:0] add_signext_15; // sfix43_E12
  wire signed [43:0] add_temp_7; // sfix44_E12
  wire signed [42:0] add_signext_16; // sfix43_E12
  wire signed [42:0] add_signext_17; // sfix43_E12
  wire signed [43:0] add_temp_8; // sfix44_E12
  reg  signed [42:0] sumdelay_pipeline2 [0:3] ; // sfix43_E12
  wire signed [42:0] sumvector3 [0:1] ; // sfix43_E12
  wire signed [42:0] add_signext_18; // sfix43_E12
  wire signed [42:0] add_signext_19; // sfix43_E12
  wire signed [43:0] add_temp_9; // sfix44_E12
  wire signed [42:0] add_signext_20; // sfix43_E12
  wire signed [42:0] add_signext_21; // sfix43_E12
  wire signed [43:0] add_temp_10; // sfix44_E12
  reg  signed [42:0] sumdelay_pipeline3 [0:1] ; // sfix43_E12
  wire signed [42:0] sum4; // sfix43_E12
  wire signed [42:0] add_signext_22; // sfix43_E12
  wire signed [42:0] add_signext_23; // sfix43_E12
  wire signed [43:0] add_temp_11; // sfix44_E12
  reg  ce_delayline1; // boolean
  reg  ce_delayline2; // boolean
  reg  ce_delayline3; // boolean
  reg  ce_delayline4; // boolean
  reg  ce_delayline5; // boolean
  reg  ce_delayline6; // boolean
  reg  ce_delayline7; // boolean
  reg  ce_delayline8; // boolean
  wire ce_gated; // boolean
  reg  signed [42:0] output_register; // sfix43_E12

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        ring_count <= 1;
      end
      else begin
        if (clk_enable == 1'b1) begin
          ring_count <= {ring_count[0], ring_count[1]};
        end
      end
    end // ce_output

  assign  phase_0 = ring_count[0]  && clk_enable;

  assign  phase_1 = ring_count[1]  && clk_enable;

  //   ------------------ CE Output Generation ------------------

  //   ------------------ CE Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output_register
      if (reset == 1'b1) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= phase_1;
      end
    end // ce_output_register

  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase0_process
      if (reset == 1'b1) begin
        input_pipeline_phase0[0] <= 0;
        input_pipeline_phase0[1] <= 0;
        input_pipeline_phase0[2] <= 0;
        input_pipeline_phase0[3] <= 0;
        input_pipeline_phase0[4] <= 0;
        input_pipeline_phase0[5] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          input_pipeline_phase0[0] <= input_register;
          input_pipeline_phase0[1] <= input_pipeline_phase0[0];
          input_pipeline_phase0[2] <= input_pipeline_phase0[1];
          input_pipeline_phase0[3] <= input_pipeline_phase0[2];
          input_pipeline_phase0[4] <= input_pipeline_phase0[3];
          input_pipeline_phase0[5] <= input_pipeline_phase0[4];
        end
      end
    end // Delay_Pipeline_Phase0_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase1_process
      if (reset == 1'b1) begin
        input_pipeline_phase1[0] <= 0;
        input_pipeline_phase1[1] <= 0;
        input_pipeline_phase1[2] <= 0;
        input_pipeline_phase1[3] <= 0;
        input_pipeline_phase1[4] <= 0;
        input_pipeline_phase1[5] <= 0;
        input_pipeline_phase1[6] <= 0;
        input_pipeline_phase1[7] <= 0;
        input_pipeline_phase1[8] <= 0;
        input_pipeline_phase1[9] <= 0;
        input_pipeline_phase1[10] <= 0;
        input_pipeline_phase1[11] <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          input_pipeline_phase1[0] <= input_register;
          input_pipeline_phase1[1] <= input_pipeline_phase1[0];
          input_pipeline_phase1[2] <= input_pipeline_phase1[1];
          input_pipeline_phase1[3] <= input_pipeline_phase1[2];
          input_pipeline_phase1[4] <= input_pipeline_phase1[3];
          input_pipeline_phase1[5] <= input_pipeline_phase1[4];
          input_pipeline_phase1[6] <= input_pipeline_phase1[5];
          input_pipeline_phase1[7] <= input_pipeline_phase1[6];
          input_pipeline_phase1[8] <= input_pipeline_phase1[7];
          input_pipeline_phase1[9] <= input_pipeline_phase1[8];
          input_pipeline_phase1[10] <= input_pipeline_phase1[9];
          input_pipeline_phase1[11] <= input_pipeline_phase1[10];
        end
      end
    end // Delay_Pipeline_Phase1_process


  assign product_phase0_7 = $signed({input_pipeline_phase0[5][23:0], 17'b00000000000000000});

  assign mul_temp = input_pipeline_phase1[0] * coeffphase2_1;
  assign product_phase1_1 = mul_temp[40:0];

  assign mul_temp_1 = input_pipeline_phase1[1] * coeffphase2_2;
  assign product_phase1_2 = mul_temp_1[40:0];

  assign mul_temp_2 = input_pipeline_phase1[2] * coeffphase2_3;
  assign product_phase1_3 = mul_temp_2[40:0];

  assign mul_temp_3 = input_pipeline_phase1[3] * coeffphase2_4;
  assign product_phase1_4 = mul_temp_3[40:0];

  assign mul_temp_4 = input_pipeline_phase1[4] * coeffphase2_5;
  assign product_phase1_5 = mul_temp_4[40:0];

  assign mul_temp_5 = input_pipeline_phase1[5] * coeffphase2_6;
  assign product_phase1_6 = mul_temp_5[40:0];

  assign mul_temp_6 = input_pipeline_phase1[6] * coeffphase2_7;
  assign product_phase1_7 = mul_temp_6[40:0];

  assign mul_temp_7 = input_pipeline_phase1[7] * coeffphase2_8;
  assign product_phase1_8 = mul_temp_7[40:0];

  assign mul_temp_8 = input_pipeline_phase1[8] * coeffphase2_9;
  assign product_phase1_9 = mul_temp_8[40:0];

  assign mul_temp_9 = input_pipeline_phase1[9] * coeffphase2_10;
  assign product_phase1_10 = mul_temp_9[40:0];

  assign mul_temp_10 = input_pipeline_phase1[10] * coeffphase2_11;
  assign product_phase1_11 = mul_temp_10[40:0];

  assign mul_temp_11 = input_pipeline_phase1[11] * coeffphase2_12;
  assign product_phase1_12 = mul_temp_11[40:0];

  always @ (posedge clk or posedge reset)
    begin: product_pipeline_process1
      if (reset == 1'b1) begin
        product_pipeline_phase1_1 <= 0;
        product_pipeline_phase1_2 <= 0;
        product_pipeline_phase1_3 <= 0;
        product_pipeline_phase1_4 <= 0;
        product_pipeline_phase1_5 <= 0;
        product_pipeline_phase1_6 <= 0;
        product_pipeline_phase0_7 <= 0;
        product_pipeline_phase1_7 <= 0;
        product_pipeline_phase1_8 <= 0;
        product_pipeline_phase1_9 <= 0;
        product_pipeline_phase1_10 <= 0;
        product_pipeline_phase1_11 <= 0;
        product_pipeline_phase1_12 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          product_pipeline_phase1_1 <= product_phase1_1;
          product_pipeline_phase1_2 <= product_phase1_2;
          product_pipeline_phase1_3 <= product_phase1_3;
          product_pipeline_phase1_4 <= product_phase1_4;
          product_pipeline_phase1_5 <= product_phase1_5;
          product_pipeline_phase1_6 <= product_phase1_6;
          product_pipeline_phase0_7 <= product_phase0_7;
          product_pipeline_phase1_7 <= product_phase1_7;
          product_pipeline_phase1_8 <= product_phase1_8;
          product_pipeline_phase1_9 <= product_phase1_9;
          product_pipeline_phase1_10 <= product_phase1_10;
          product_pipeline_phase1_11 <= product_phase1_11;
          product_pipeline_phase1_12 <= product_phase1_12;
        end
      end
    end // product_pipeline_process1

  assign add_signext = product_pipeline_phase1_1;
  assign add_signext_1 = product_pipeline_phase1_2;
  assign add_temp = add_signext + add_signext_1;
  assign sumvector1[0] = $signed({{1{add_temp[41]}}, add_temp});

  assign add_signext_2 = product_pipeline_phase1_3;
  assign add_signext_3 = product_pipeline_phase1_4;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sumvector1[1] = $signed({{1{add_temp_1[41]}}, add_temp_1});

  assign add_signext_4 = product_pipeline_phase1_5;
  assign add_signext_5 = product_pipeline_phase1_6;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sumvector1[2] = $signed({{1{add_temp_2[41]}}, add_temp_2});

  assign add_signext_6 = product_pipeline_phase1_7;
  assign add_signext_7 = product_pipeline_phase1_8;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sumvector1[3] = $signed({{1{add_temp_3[41]}}, add_temp_3});

  assign add_signext_8 = product_pipeline_phase1_9;
  assign add_signext_9 = product_pipeline_phase1_10;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sumvector1[4] = $signed({{1{add_temp_4[41]}}, add_temp_4});

  assign add_signext_10 = product_pipeline_phase1_11;
  assign add_signext_11 = product_pipeline_phase1_12;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sumvector1[5] = $signed({{1{add_temp_5[41]}}, add_temp_5});

  assign sumvector1[6] = $signed({{2{product_pipeline_phase0_7[40]}}, product_pipeline_phase0_7});

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process1
      if (reset == 1'b1) begin
        sumdelay_pipeline1[0] <= 0;
        sumdelay_pipeline1[1] <= 0;
        sumdelay_pipeline1[2] <= 0;
        sumdelay_pipeline1[3] <= 0;
        sumdelay_pipeline1[4] <= 0;
        sumdelay_pipeline1[5] <= 0;
        sumdelay_pipeline1[6] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          sumdelay_pipeline1[0] <= sumvector1[0];
          sumdelay_pipeline1[1] <= sumvector1[1];
          sumdelay_pipeline1[2] <= sumvector1[2];
          sumdelay_pipeline1[3] <= sumvector1[3];
          sumdelay_pipeline1[4] <= sumvector1[4];
          sumdelay_pipeline1[5] <= sumvector1[5];
          sumdelay_pipeline1[6] <= sumvector1[6];
        end
      end
    end // sumdelay_pipeline_process1

  assign add_signext_12 = sumdelay_pipeline1[0];
  assign add_signext_13 = sumdelay_pipeline1[1];
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sumvector2[0] = add_temp_6[42:0];

  assign add_signext_14 = sumdelay_pipeline1[2];
  assign add_signext_15 = sumdelay_pipeline1[3];
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sumvector2[1] = add_temp_7[42:0];

  assign add_signext_16 = sumdelay_pipeline1[4];
  assign add_signext_17 = sumdelay_pipeline1[5];
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sumvector2[2] = add_temp_8[42:0];

  assign sumvector2[3] = sumdelay_pipeline1[6];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process2
      if (reset == 1'b1) begin
        sumdelay_pipeline2[0] <= 0;
        sumdelay_pipeline2[1] <= 0;
        sumdelay_pipeline2[2] <= 0;
        sumdelay_pipeline2[3] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          sumdelay_pipeline2[0] <= sumvector2[0];
          sumdelay_pipeline2[1] <= sumvector2[1];
          sumdelay_pipeline2[2] <= sumvector2[2];
          sumdelay_pipeline2[3] <= sumvector2[3];
        end
      end
    end // sumdelay_pipeline_process2

  assign add_signext_18 = sumdelay_pipeline2[0];
  assign add_signext_19 = sumdelay_pipeline2[1];
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sumvector3[0] = add_temp_9[42:0];

  assign add_signext_20 = sumdelay_pipeline2[2];
  assign add_signext_21 = sumdelay_pipeline2[3];
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sumvector3[1] = add_temp_10[42:0];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process3
      if (reset == 1'b1) begin
        sumdelay_pipeline3[0] <= 0;
        sumdelay_pipeline3[1] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          sumdelay_pipeline3[0] <= sumvector3[0];
          sumdelay_pipeline3[1] <= sumvector3[1];
        end
      end
    end // sumdelay_pipeline_process3

  assign add_signext_22 = sumdelay_pipeline3[0];
  assign add_signext_23 = sumdelay_pipeline3[1];
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum4 = add_temp_11[42:0];

  always @ (posedge clk or posedge reset)
    begin: ce_delay
      if (reset == 1'b1) begin
        ce_delayline1 <= 1'b0;
        ce_delayline2 <= 1'b0;
        ce_delayline3 <= 1'b0;
        ce_delayline4 <= 1'b0;
        ce_delayline5 <= 1'b0;
        ce_delayline6 <= 1'b0;
        ce_delayline7 <= 1'b0;
        ce_delayline8 <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          ce_delayline1 <= clk_enable;
          ce_delayline2 <= ce_delayline1;
          ce_delayline3 <= ce_delayline2;
          ce_delayline4 <= ce_delayline3;
          ce_delayline5 <= ce_delayline4;
          ce_delayline6 <= ce_delayline5;
          ce_delayline7 <= ce_delayline6;
          ce_delayline8 <= ce_delayline7;
        end
      end
    end // ce_delay

  assign ce_gated =  ce_delayline8 & ce_out_reg;

  always @ (posedge clk or posedge reset)
    begin: output_register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          output_register <= sum4;
        end
      end
    end // output_register_process

  // Assignment Statements
  assign ce_out = ce_gated;
  assign filter_out = output_register;
endmodule  // HB_2_pl
