#!/bin/bash
PREFIX=/usr/local
rm -rf $PREFIX/bin/gr_plot_*
rm -rf $PREFIX/bin/usrp*
rm -rf $PREFIX/bin/grc
rm -rf $PREFIX/bin/find_usrps
rm -rf $PREFIX/bin/lsusrp
rm -rf $PREFIX/bin/test_all
rm -rf $PREFIX/etc/gnuradio
rm -rf $PREFIX/include/gnuradio
rm -rf $PREFIX/include/gruel
rm -rf $PREFIX/include/fpga_*
rm -rf $PREFIX/include/mb_*
rm -rf $PREFIX/include/mblock
rm -rf $PREFIX/include/pmt*
rm -rf $PREFIX/include/usrp*
rm -rf $PREFIX/lib/libgnuradio*
rm -rf $PREFIX/lib/libgr*
rm -rf $PREFIX/lib/libmblock*
rm -rf $PREFIX/lib/libpmt*
rm -rf $PREFIX/lib/libusrp*
rm -rf $PREFIX/lib/python2.7/site-packages/gnuradio
rm -rf $PREFIX/lib/python2.7/site-packages/usrpm
rm -rf $PREFIX/lib/python2.7/site-packages/grc
rm -rf $PREFIX/lib/python2.7/site-packages/grc_gnuradio
rm -rf $PREFIX/lib/pkgconfig/gnuradio*.pc
rm -rf $PREFIX/lib/pkgconfig/gr-wxgui*.pc
rm -rf $PREFIX/lib/pkgconfig/gruel.pc
rm -rf $PREFIX/lib/pkgconfig/mblock.pc
rm -rf $PREFIX/lib/pkgconfig/pmt.pc
rm -rf $PREFIX/lib/pkgconfig/usrp*.pc
rm -rf $PREFIX/share/doc/gnuradio*
rm -rf $PREFIX/share/doc/usrp*
rm -rf $PREFIX/share/gnuradio
rm -rf $PREFIX/share/grc
rm -rf $PREFIX/share/usrp
ldconfig

