// -------------------------------------------------------------
//
// Module: CIC4_65_m
//
// Generated by MATLAB(R) 7.2 and the Filter Design HDL Coder 1.4.
//
// Generated on: 2007-02-09 09:28:55
//
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetLanguage: Verilog
// Name: CIC4_65_m
// TargetDirectory: C:\Data\QS\QuickSilver\trunk\QS1R_AB_QUARTUS\CIC
// OptimizeForHDL: On
// SerialPartition: -1
// InlineConfigurations: Off
// SafeZeroConcat: Off
// CastBeforeSum: On
// TestBenchStimulus: step ramp chirp noise 
//
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure        : Cascaded Integrator-Comb Decimator
// Decimation Factor       : 65
// Differential Delay      : 1
// Number of Sections      : 4
// Stable                  : Yes
// Linear Phase            : Yes (Type 1)
//
// Input                   : s20,15
// Output                  : s24,-6
// Filter Internals        : Minimum Word Lengths
//   Integrator Section 1  : s45,15
//   Integrator Section 2  : s41,11
//   Integrator Section 3  : s36,6
//   Integrator Section 4  : s31,1
//   Comb Section 1        : s29,-1
//   Comb Section 2        : s28,-2
//   Comb Section 3        : s27,-3
//   Comb Section 4        : s26,-4
//
// Implementation Cost
// Number of Multipliers : 0
// Number of Adders      : 8
// Number of States      : 8
// MultPerInputSample    : 0
// AddPerInputSample     : 4.0615
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC4_65_m 
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [19:0] filter_in; //sfix20_En15
  output  signed [23:0] filter_out; //sfix24_E6
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: CIC4_65_m
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  // Signals
  reg  [6:0] cur_count; // ufix7
  wire phase_1; // boolean
  reg  ce_out_reg; // boolean
  //   
  reg  signed [19:0] input_register; // sfix20_En15
  //   -- Section 1 Signals 
  wire signed [19:0] section_in1; // sfix20_En15
  wire signed [44:0] section_cast1; // sfix45_En15
  wire signed [44:0] sum1; // sfix45_En15
  reg  signed [44:0] section_out1; // sfix45_En15
  wire signed [44:0] add_cast; // sfix45_En15
  wire signed [44:0] add_cast_1; // sfix45_En15
  wire signed [45:0] add_temp; // sfix46_En15
  //   -- Section 2 Signals 
  wire signed [44:0] section_in2; // sfix45_En15
  wire signed [40:0] section_cast2; // sfix41_En11
  wire signed [40:0] sum2; // sfix41_En11
  reg  signed [40:0] section_out2; // sfix41_En11
  wire signed [40:0] add_cast_2; // sfix41_En11
  wire signed [40:0] add_cast_3; // sfix41_En11
  wire signed [41:0] add_temp_1; // sfix42_En11
  //   -- Section 3 Signals 
  wire signed [40:0] section_in3; // sfix41_En11
  wire signed [35:0] section_cast3; // sfix36_En6
  wire signed [35:0] sum3; // sfix36_En6
  reg  signed [35:0] section_out3; // sfix36_En6
  wire signed [35:0] add_cast_4; // sfix36_En6
  wire signed [35:0] add_cast_5; // sfix36_En6
  wire signed [36:0] add_temp_2; // sfix37_En6
  //   -- Section 4 Signals 
  wire signed [35:0] section_in4; // sfix36_En6
  wire signed [30:0] section_cast4; // sfix31_En1
  wire signed [30:0] sum4; // sfix31_En1
  reg  signed [30:0] section_out4; // sfix31_En1
  wire signed [30:0] add_cast_6; // sfix31_En1
  wire signed [30:0] add_cast_7; // sfix31_En1
  wire signed [31:0] add_temp_3; // sfix32_En1
  //   -- Section 5 Signals 
  wire signed [30:0] section_in5; // sfix31_En1
  wire signed [28:0] section_cast5; // sfix29_E1
  reg  signed [28:0] diff1; // sfix29_E1
  wire signed [28:0] section_out5; // sfix29_E1
  wire signed [28:0] sub_cast; // sfix29_E1
  wire signed [28:0] sub_cast_1; // sfix29_E1
  wire signed [29:0] sub_temp; // sfix30_E1
  //   -- Section 6 Signals 
  wire signed [28:0] section_in6; // sfix29_E1
  wire signed [27:0] section_cast6; // sfix28_E2
  reg  signed [27:0] diff2; // sfix28_E2
  wire signed [27:0] section_out6; // sfix28_E2
  wire signed [27:0] sub_cast_2; // sfix28_E2
  wire signed [27:0] sub_cast_3; // sfix28_E2
  wire signed [28:0] sub_temp_1; // sfix29_E2
  //   -- Section 7 Signals 
  wire signed [27:0] section_in7; // sfix28_E2
  wire signed [26:0] section_cast7; // sfix27_E3
  reg  signed [26:0] diff3; // sfix27_E3
  wire signed [26:0] section_out7; // sfix27_E3
  wire signed [26:0] sub_cast_4; // sfix27_E3
  wire signed [26:0] sub_cast_5; // sfix27_E3
  wire signed [27:0] sub_temp_2; // sfix28_E3
  //   -- Section 8 Signals 
  wire signed [26:0] section_in8; // sfix27_E3
  wire signed [25:0] section_cast8; // sfix26_E4
  reg  signed [25:0] diff4; // sfix26_E4
  wire signed [25:0] section_out8; // sfix26_E4
  wire signed [25:0] sub_cast_6; // sfix26_E4
  wire signed [25:0] sub_cast_7; // sfix26_E4
  wire signed [26:0] sub_temp_3; // sfix27_E4
  wire signed [23:0] output_typeconvert; // sfix24_E6
  //   
  reg  signed [23:0] output_register; // sfix24_E6

  // Block Statements
  //   ------------------ CE Output Generation ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 7'b0000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count == 7'b1000000) begin
            cur_count <= 7'b0000000;
          end
          else begin
            cur_count <= cur_count + 1;
          end
        end
      end
    end // ce_output

  assign  phase_1 = (cur_count == 7'b0000001 && clk_enable == 1'b1)? 1 : 0;

  //   ------------------ CE Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output_register
      if (reset == 1'b1) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= phase_1;
      end
    end // ce_output_register

  //   ------------------ Input Register ------------------

  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  //   ------------------ Section # 1 : Integrator ------------------

  assign section_in1 = input_register;

  assign section_cast1 = $signed({{25{section_in1[19]}}, section_in1});

  assign add_cast = section_cast1;
  assign add_cast_1 = section_out1;
  assign add_temp = add_cast + add_cast_1;
  assign sum1 = add_temp[44:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section1
      if (reset == 1'b1) begin
        section_out1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out1 <= sum1;
        end
      end
    end // integrator_delay_section1

  //   ------------------ Section # 2 : Integrator ------------------

  assign section_in2 = section_out1;

  assign section_cast2 = section_in2[44:4];

  assign add_cast_2 = section_cast2;
  assign add_cast_3 = section_out2;
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign sum2 = add_temp_1[40:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section2
      if (reset == 1'b1) begin
        section_out2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out2 <= sum2;
        end
      end
    end // integrator_delay_section2

  //   ------------------ Section # 3 : Integrator ------------------

  assign section_in3 = section_out2;

  assign section_cast3 = section_in3[40:5];

  assign add_cast_4 = section_cast3;
  assign add_cast_5 = section_out3;
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign sum3 = add_temp_2[35:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section3
      if (reset == 1'b1) begin
        section_out3 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out3 <= sum3;
        end
      end
    end // integrator_delay_section3

  //   ------------------ Section # 4 : Integrator ------------------

  assign section_in4 = section_out3;

  assign section_cast4 = section_in4[35:5];

  assign add_cast_6 = section_cast4;
  assign add_cast_7 = section_out4;
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign sum4 = add_temp_3[30:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section4
      if (reset == 1'b1) begin
        section_out4 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out4 <= sum4;
        end
      end
    end // integrator_delay_section4

  //   ------------------ Section # 5 : Comb ------------------

  assign section_in5 = section_out4;

  assign section_cast5 = section_in5[30:2];

  assign sub_cast = section_cast5;
  assign sub_cast_1 = diff1;
  assign sub_temp = sub_cast - sub_cast_1;
  assign section_out5 = sub_temp[28:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section5
      if (reset == 1'b1) begin
        diff1 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff1 <= section_cast5;
        end
      end
    end // comb_delay_section5

  //   ------------------ Section # 6 : Comb ------------------

  assign section_in6 = section_out5;

  assign section_cast6 = section_in6[28:1];

  assign sub_cast_2 = section_cast6;
  assign sub_cast_3 = diff2;
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign section_out6 = sub_temp_1[27:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section6
      if (reset == 1'b1) begin
        diff2 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff2 <= section_cast6;
        end
      end
    end // comb_delay_section6

  //   ------------------ Section # 7 : Comb ------------------

  assign section_in7 = section_out6;

  assign section_cast7 = section_in7[27:1];

  assign sub_cast_4 = section_cast7;
  assign sub_cast_5 = diff3;
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign section_out7 = sub_temp_2[26:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section7
      if (reset == 1'b1) begin
        diff3 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff3 <= section_cast7;
        end
      end
    end // comb_delay_section7

  //   ------------------ Section # 8 : Comb ------------------

  assign section_in8 = section_out7;

  assign section_cast8 = section_in8[26:1];

  assign sub_cast_6 = section_cast8;
  assign sub_cast_7 = diff4;
  assign sub_temp_3 = sub_cast_6 - sub_cast_7;
  assign section_out8 = sub_temp_3[25:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section8
      if (reset == 1'b1) begin
        diff4 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff4 <= section_cast8;
        end
      end
    end // comb_delay_section8

  assign output_typeconvert = section_out8[25:2];

  //   ------------------ Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: output_reg_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // output_reg_process

  // Assignment Statements
  assign ce_out = ce_out_reg;
  assign filter_out = output_register;
endmodule  // CIC4_65_m
