// -------------------------------------------------------------
//
// Module: CIC6_65
//
// Generated by MATLAB(R) 7.2 and the Filter Design HDL Coder 1.4.
//
// Generated on: 2007-02-08 15:11:38
//
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetLanguage: Verilog
// Name: CIC6_65
// TargetDirectory: C:\Data\QS\QuickSilver\trunk\QS1R_AB_QUARTUS\CIC
// OptimizeForHDL: On
// SerialPartition: -1
// InlineConfigurations: Off
// SafeZeroConcat: Off
// CastBeforeSum: On
// TestBenchStimulus: step ramp chirp noise 
//
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure        : Cascaded Integrator-Comb Decimator
// Decimation Factor       : 65
// Differential Delay      : 1
// Number of Sections      : 6
// Stable                  : Yes
// Linear Phase            : Yes (Type 1)
//
// Input                   : s20,15
// Output                  : s32,-10
// Filter Internals        : Minimum Word Lengths
//   Integrator Section 1  : s57,15
//   Integrator Section 2  : s57,15
//   Integrator Section 3  : s55,13
//   Integrator Section 4  : s50,8
//   Integrator Section 5  : s46,4
//   Integrator Section 6  : s41,-1
//   Comb Section 1        : s39,-3
//   Comb Section 2        : s38,-4
//   Comb Section 3        : s37,-5
//   Comb Section 4        : s36,-6
//   Comb Section 5        : s36,-6
//   Comb Section 6        : s35,-7
//
// Implementation Cost
// Number of Multipliers : 0
// Number of Adders      : 12
// Number of States      : 12
// MultPerInputSample    : 0
// AddPerInputSample     : 6.0923
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC6_65 
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [19:0] filter_in; //sfix20_En15
  output  signed [31:0] filter_out; //sfix32_E10
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: CIC6_65
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  // Signals
  reg  [6:0] cur_count; // ufix7
  wire phase_1; // boolean
  reg  ce_out_reg; // boolean
  //   
  reg  signed [19:0] input_register; // sfix20_En15
  //   -- Section 1 Signals 
  wire signed [19:0] section_in1; // sfix20_En15
  wire signed [56:0] section_cast1; // sfix57_En15
  wire signed [56:0] sum1; // sfix57_En15
  reg  signed [56:0] section_out1; // sfix57_En15
  wire signed [56:0] add_cast; // sfix57_En15
  wire signed [56:0] add_cast_1; // sfix57_En15
  wire signed [57:0] add_temp; // sfix58_En15
  //   -- Section 2 Signals 
  wire signed [56:0] section_in2; // sfix57_En15
  wire signed [56:0] sum2; // sfix57_En15
  reg  signed [56:0] section_out2; // sfix57_En15
  wire signed [56:0] add_cast_2; // sfix57_En15
  wire signed [56:0] add_cast_3; // sfix57_En15
  wire signed [57:0] add_temp_1; // sfix58_En15
  //   -- Section 3 Signals 
  wire signed [56:0] section_in3; // sfix57_En15
  wire signed [54:0] section_cast3; // sfix55_En13
  wire signed [54:0] sum3; // sfix55_En13
  reg  signed [54:0] section_out3; // sfix55_En13
  wire signed [54:0] add_cast_4; // sfix55_En13
  wire signed [54:0] add_cast_5; // sfix55_En13
  wire signed [55:0] add_temp_2; // sfix56_En13
  //   -- Section 4 Signals 
  wire signed [54:0] section_in4; // sfix55_En13
  wire signed [49:0] section_cast4; // sfix50_En8
  wire signed [49:0] sum4; // sfix50_En8
  reg  signed [49:0] section_out4; // sfix50_En8
  wire signed [49:0] add_cast_6; // sfix50_En8
  wire signed [49:0] add_cast_7; // sfix50_En8
  wire signed [50:0] add_temp_3; // sfix51_En8
  //   -- Section 5 Signals 
  wire signed [49:0] section_in5; // sfix50_En8
  wire signed [45:0] section_cast5; // sfix46_En4
  wire signed [45:0] sum5; // sfix46_En4
  reg  signed [45:0] section_out5; // sfix46_En4
  wire signed [45:0] add_cast_8; // sfix46_En4
  wire signed [45:0] add_cast_9; // sfix46_En4
  wire signed [46:0] add_temp_4; // sfix47_En4
  //   -- Section 6 Signals 
  wire signed [45:0] section_in6; // sfix46_En4
  wire signed [40:0] section_cast6; // sfix41_E1
  wire signed [40:0] sum6; // sfix41_E1
  reg  signed [40:0] section_out6; // sfix41_E1
  wire signed [40:0] add_cast_10; // sfix41_E1
  wire signed [40:0] add_cast_11; // sfix41_E1
  wire signed [41:0] add_temp_5; // sfix42_E1
  //   -- Section 7 Signals 
  wire signed [40:0] section_in7; // sfix41_E1
  wire signed [38:0] section_cast7; // sfix39_E3
  reg  signed [38:0] diff1; // sfix39_E3
  wire signed [38:0] section_out7; // sfix39_E3
  wire signed [38:0] sub_cast; // sfix39_E3
  wire signed [38:0] sub_cast_1; // sfix39_E3
  wire signed [39:0] sub_temp; // sfix40_E3
  //   -- Section 8 Signals 
  wire signed [38:0] section_in8; // sfix39_E3
  wire signed [37:0] section_cast8; // sfix38_E4
  reg  signed [37:0] diff2; // sfix38_E4
  wire signed [37:0] section_out8; // sfix38_E4
  wire signed [37:0] sub_cast_2; // sfix38_E4
  wire signed [37:0] sub_cast_3; // sfix38_E4
  wire signed [38:0] sub_temp_1; // sfix39_E4
  //   -- Section 9 Signals 
  wire signed [37:0] section_in9; // sfix38_E4
  wire signed [36:0] section_cast9; // sfix37_E5
  reg  signed [36:0] diff3; // sfix37_E5
  wire signed [36:0] section_out9; // sfix37_E5
  wire signed [36:0] sub_cast_4; // sfix37_E5
  wire signed [36:0] sub_cast_5; // sfix37_E5
  wire signed [37:0] sub_temp_2; // sfix38_E5
  //   -- Section 10 Signals 
  wire signed [36:0] section_in10; // sfix37_E5
  wire signed [35:0] section_cast10; // sfix36_E6
  reg  signed [35:0] diff4; // sfix36_E6
  wire signed [35:0] section_out10; // sfix36_E6
  wire signed [35:0] sub_cast_6; // sfix36_E6
  wire signed [35:0] sub_cast_7; // sfix36_E6
  wire signed [36:0] sub_temp_3; // sfix37_E6
  //   -- Section 11 Signals 
  wire signed [35:0] section_in11; // sfix36_E6
  reg  signed [35:0] diff5; // sfix36_E6
  wire signed [35:0] section_out11; // sfix36_E6
  wire signed [35:0] sub_cast_8; // sfix36_E6
  wire signed [35:0] sub_cast_9; // sfix36_E6
  wire signed [36:0] sub_temp_4; // sfix37_E6
  //   -- Section 12 Signals 
  wire signed [35:0] section_in12; // sfix36_E6
  wire signed [34:0] section_cast12; // sfix35_E7
  reg  signed [34:0] diff6; // sfix35_E7
  wire signed [34:0] section_out12; // sfix35_E7
  wire signed [34:0] sub_cast_10; // sfix35_E7
  wire signed [34:0] sub_cast_11; // sfix35_E7
  wire signed [35:0] sub_temp_5; // sfix36_E7
  wire signed [31:0] output_typeconvert; // sfix32_E10
  //   
  reg  signed [31:0] output_register; // sfix32_E10

  // Block Statements
  //   ------------------ CE Output Generation ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 7'b0000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count == 7'b1000000) begin
            cur_count <= 7'b0000000;
          end
          else begin
            cur_count <= cur_count + 1;
          end
        end
      end
    end // ce_output

  assign  phase_1 = (cur_count == 7'b0000001 && clk_enable == 1'b1)? 1 : 0;

  //   ------------------ CE Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output_register
      if (reset == 1'b1) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= phase_1;
      end
    end // ce_output_register

  //   ------------------ Input Register ------------------

  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  //   ------------------ Section # 1 : Integrator ------------------

  assign section_in1 = input_register;

  assign section_cast1 = $signed({{37{section_in1[19]}}, section_in1});

  assign add_cast = section_cast1;
  assign add_cast_1 = section_out1;
  assign add_temp = add_cast + add_cast_1;
  assign sum1 = add_temp[56:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section1
      if (reset == 1'b1) begin
        section_out1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out1 <= sum1;
        end
      end
    end // integrator_delay_section1

  //   ------------------ Section # 2 : Integrator ------------------

  assign section_in2 = section_out1;

  assign add_cast_2 = section_in2;
  assign add_cast_3 = section_out2;
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign sum2 = add_temp_1[56:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section2
      if (reset == 1'b1) begin
        section_out2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out2 <= sum2;
        end
      end
    end // integrator_delay_section2

  //   ------------------ Section # 3 : Integrator ------------------

  assign section_in3 = section_out2;

  assign section_cast3 = section_in3[56:2];

  assign add_cast_4 = section_cast3;
  assign add_cast_5 = section_out3;
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign sum3 = add_temp_2[54:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section3
      if (reset == 1'b1) begin
        section_out3 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out3 <= sum3;
        end
      end
    end // integrator_delay_section3

  //   ------------------ Section # 4 : Integrator ------------------

  assign section_in4 = section_out3;

  assign section_cast4 = section_in4[54:5];

  assign add_cast_6 = section_cast4;
  assign add_cast_7 = section_out4;
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign sum4 = add_temp_3[49:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section4
      if (reset == 1'b1) begin
        section_out4 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out4 <= sum4;
        end
      end
    end // integrator_delay_section4

  //   ------------------ Section # 5 : Integrator ------------------

  assign section_in5 = section_out4;

  assign section_cast5 = section_in5[49:4];

  assign add_cast_8 = section_cast5;
  assign add_cast_9 = section_out5;
  assign add_temp_4 = add_cast_8 + add_cast_9;
  assign sum5 = add_temp_4[45:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section5
      if (reset == 1'b1) begin
        section_out5 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out5 <= sum5;
        end
      end
    end // integrator_delay_section5

  //   ------------------ Section # 6 : Integrator ------------------

  assign section_in6 = section_out5;

  assign section_cast6 = section_in6[45:5];

  assign add_cast_10 = section_cast6;
  assign add_cast_11 = section_out6;
  assign add_temp_5 = add_cast_10 + add_cast_11;
  assign sum6 = add_temp_5[40:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section6
      if (reset == 1'b1) begin
        section_out6 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out6 <= sum6;
        end
      end
    end // integrator_delay_section6

  //   ------------------ Section # 7 : Comb ------------------

  assign section_in7 = section_out6;

  assign section_cast7 = section_in7[40:2];

  assign sub_cast = section_cast7;
  assign sub_cast_1 = diff1;
  assign sub_temp = sub_cast - sub_cast_1;
  assign section_out7 = sub_temp[38:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section7
      if (reset == 1'b1) begin
        diff1 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff1 <= section_cast7;
        end
      end
    end // comb_delay_section7

  //   ------------------ Section # 8 : Comb ------------------

  assign section_in8 = section_out7;

  assign section_cast8 = section_in8[38:1];

  assign sub_cast_2 = section_cast8;
  assign sub_cast_3 = diff2;
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign section_out8 = sub_temp_1[37:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section8
      if (reset == 1'b1) begin
        diff2 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff2 <= section_cast8;
        end
      end
    end // comb_delay_section8

  //   ------------------ Section # 9 : Comb ------------------

  assign section_in9 = section_out8;

  assign section_cast9 = section_in9[37:1];

  assign sub_cast_4 = section_cast9;
  assign sub_cast_5 = diff3;
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign section_out9 = sub_temp_2[36:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section9
      if (reset == 1'b1) begin
        diff3 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff3 <= section_cast9;
        end
      end
    end // comb_delay_section9

  //   ------------------ Section # 10 : Comb ------------------

  assign section_in10 = section_out9;

  assign section_cast10 = section_in10[36:1];

  assign sub_cast_6 = section_cast10;
  assign sub_cast_7 = diff4;
  assign sub_temp_3 = sub_cast_6 - sub_cast_7;
  assign section_out10 = sub_temp_3[35:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section10
      if (reset == 1'b1) begin
        diff4 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff4 <= section_cast10;
        end
      end
    end // comb_delay_section10

  //   ------------------ Section # 11 : Comb ------------------

  assign section_in11 = section_out10;

  assign sub_cast_8 = section_in11;
  assign sub_cast_9 = diff5;
  assign sub_temp_4 = sub_cast_8 - sub_cast_9;
  assign section_out11 = sub_temp_4[35:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section11
      if (reset == 1'b1) begin
        diff5 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff5 <= section_in11;
        end
      end
    end // comb_delay_section11

  //   ------------------ Section # 12 : Comb ------------------

  assign section_in12 = section_out11;

  assign section_cast12 = section_in12[35:1];

  assign sub_cast_10 = section_cast12;
  assign sub_cast_11 = diff6;
  assign sub_temp_5 = sub_cast_10 - sub_cast_11;
  assign section_out12 = sub_temp_5[34:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section12
      if (reset == 1'b1) begin
        diff6 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff6 <= section_cast12;
        end
      end
    end // comb_delay_section12

  assign output_typeconvert = section_out12[34:3];

  //   ------------------ Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: output_reg_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // output_reg_process

  // Assignment Statements
  assign ce_out = ce_out_reg;
  assign filter_out = output_register;
endmodule  // CIC6_65
