//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thetis.DJConsoleUI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class MappingMP3e2 : global::System.Configuration.ApplicationSettingsBase {
        
        private static MappingMP3e2 defaultInstance = ((MappingMP3e2)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MappingMP3e2())));
        
        public static MappingMP3e2 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_BassA {
            get {
                return ((int)(this["DJConsole_BassA"]));
            }
            set {
                this["DJConsole_BassA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_BassB {
            get {
                return ((int)(this["DJConsole_BassB"]));
            }
            set {
                this["DJConsole_BassB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_Crossfader {
            get {
                return ((int)(this["DJConsole_Crossfader"]));
            }
            set {
                this["DJConsole_Crossfader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_CueA {
            get {
                return ((int)(this["DJConsole_CueA"]));
            }
            set {
                this["DJConsole_CueA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_CueB {
            get {
                return ((int)(this["DJConsole_CueB"]));
            }
            set {
                this["DJConsole_CueB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_JogWheelA {
            get {
                return ((int)(this["DJConsole_JogWheelA"]));
            }
            set {
                this["DJConsole_JogWheelA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_JogWheelB {
            get {
                return ((int)(this["DJConsole_JogWheelB"]));
            }
            set {
                this["DJConsole_JogWheelB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_MediumA {
            get {
                return ((int)(this["DJConsole_MediumA"]));
            }
            set {
                this["DJConsole_MediumA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_MediumB {
            get {
                return ((int)(this["DJConsole_MediumB"]));
            }
            set {
                this["DJConsole_MediumB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_PitchA {
            get {
                return ((int)(this["DJConsole_PitchA"]));
            }
            set {
                this["DJConsole_PitchA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_PitchB {
            get {
                return ((int)(this["DJConsole_PitchB"]));
            }
            set {
                this["DJConsole_PitchB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_PitchDownA {
            get {
                return ((int)(this["DJConsole_PitchDownA"]));
            }
            set {
                this["DJConsole_PitchDownA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_PitchDownB {
            get {
                return ((int)(this["DJConsole_PitchDownB"]));
            }
            set {
                this["DJConsole_PitchDownB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_PitchUpA {
            get {
                return ((int)(this["DJConsole_PitchUpA"]));
            }
            set {
                this["DJConsole_PitchUpA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_PitchUpB {
            get {
                return ((int)(this["DJConsole_PitchUpB"]));
            }
            set {
                this["DJConsole_PitchUpB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_PlayA {
            get {
                return ((int)(this["DJConsole_PlayA"]));
            }
            set {
                this["DJConsole_PlayA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_PlayB {
            get {
                return ((int)(this["DJConsole_PlayB"]));
            }
            set {
                this["DJConsole_PlayB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_TrebleB {
            get {
                return ((int)(this["DJConsole_TrebleB"]));
            }
            set {
                this["DJConsole_TrebleB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_TrackNextA {
            get {
                return ((int)(this["DJConsole_TrackNextA"]));
            }
            set {
                this["DJConsole_TrackNextA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_TrackNextB {
            get {
                return ((int)(this["DJConsole_TrackNextB"]));
            }
            set {
                this["DJConsole_TrackNextB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_TrackPrevA {
            get {
                return ((int)(this["DJConsole_TrackPrevA"]));
            }
            set {
                this["DJConsole_TrackPrevA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_TrackPrevB {
            get {
                return ((int)(this["DJConsole_TrackPrevB"]));
            }
            set {
                this["DJConsole_TrackPrevB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_TrebleA {
            get {
                return ((int)(this["DJConsole_TrebleA"]));
            }
            set {
                this["DJConsole_TrebleA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_VolumeA {
            get {
                return ((int)(this["DJConsole_VolumeA"]));
            }
            set {
                this["DJConsole_VolumeA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_VolumeB {
            get {
                return ((int)(this["DJConsole_VolumeB"]));
            }
            set {
                this["DJConsole_VolumeB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_MasterTempoA {
            get {
                return ((int)(this["DJConsole_MasterTempoA"]));
            }
            set {
                this["DJConsole_MasterTempoA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_MasterTempoB {
            get {
                return ((int)(this["DJConsole_MasterTempoB"]));
            }
            set {
                this["DJConsole_MasterTempoB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_OneA {
            get {
                return ((int)(this["DJConsole_OneA"]));
            }
            set {
                this["DJConsole_OneA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_OneB {
            get {
                return ((int)(this["DJConsole_OneB"]));
            }
            set {
                this["DJConsole_OneB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_TwoA {
            get {
                return ((int)(this["DJConsole_TwoA"]));
            }
            set {
                this["DJConsole_TwoA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_TwoB {
            get {
                return ((int)(this["DJConsole_TwoB"]));
            }
            set {
                this["DJConsole_TwoB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_ThreeA {
            get {
                return ((int)(this["DJConsole_ThreeA"]));
            }
            set {
                this["DJConsole_ThreeA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_ThreeB {
            get {
                return ((int)(this["DJConsole_ThreeB"]));
            }
            set {
                this["DJConsole_ThreeB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_FourA {
            get {
                return ((int)(this["DJConsole_FourA"]));
            }
            set {
                this["DJConsole_FourA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_FourB {
            get {
                return ((int)(this["DJConsole_FourB"]));
            }
            set {
                this["DJConsole_FourB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_SyncA {
            get {
                return ((int)(this["DJConsole_SyncA"]));
            }
            set {
                this["DJConsole_SyncA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_SyncB {
            get {
                return ((int)(this["DJConsole_SyncB"]));
            }
            set {
                this["DJConsole_SyncB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_Up {
            get {
                return ((int)(this["DJConsole_Up"]));
            }
            set {
                this["DJConsole_Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_Down {
            get {
                return ((int)(this["DJConsole_Down"]));
            }
            set {
                this["DJConsole_Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_ListenA {
            get {
                return ((int)(this["DJConsole_ListenA"]));
            }
            set {
                this["DJConsole_ListenA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_ListenB {
            get {
                return ((int)(this["DJConsole_ListenB"]));
            }
            set {
                this["DJConsole_ListenB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_Files {
            get {
                return ((int)(this["DJConsole_Files"]));
            }
            set {
                this["DJConsole_Files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_Folders {
            get {
                return ((int)(this["DJConsole_Folders"]));
            }
            set {
                this["DJConsole_Folders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_LoadA {
            get {
                return ((int)(this["DJConsole_LoadA"]));
            }
            set {
                this["DJConsole_LoadA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_LoadB {
            get {
                return ((int)(this["DJConsole_LoadB"]));
            }
            set {
                this["DJConsole_LoadB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_Scratch {
            get {
                return ((int)(this["DJConsole_Scratch"]));
            }
            set {
                this["DJConsole_Scratch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_Automix {
            get {
                return ((int)(this["DJConsole_Automix"]));
            }
            set {
                this["DJConsole_Automix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_ShiftA {
            get {
                return ((int)(this["DJConsole_ShiftA"]));
            }
            set {
                this["DJConsole_ShiftA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DJConsole_ShiftB {
            get {
                return ((int)(this["DJConsole_ShiftB"]));
            }
            set {
                this["DJConsole_ShiftB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting {
            get {
                return ((int)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
