/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WaterfallPanel.java
 *
 * Created on 20-Jan-2010, 09:42:39
 */

package jmonitor;

import java.awt.Color;
import java.awt.Image;

/**
 *
 * @author john
 */
public class WaterfallPanel extends javax.swing.JPanel {

    /** Creates new form WaterfallPanel */
    public WaterfallPanel() {
        initComponents();
        pixels=new int[WIDTH*HEIGHT];
        for(int i=0;i<pixels.length;i++) {
            pixels[i]=255<<24;
        }
    }
    
    protected void paintComponent(java.awt.Graphics g) {
        Image waterfallImage=java.awt.Toolkit.getDefaultToolkit().createImage(new java.awt.image.MemoryImageSource(WIDTH,HEIGHT,pixels,0,WIDTH));
        g.drawImage(waterfallImage,0,0,null);
    }

    public void updateWaterfall(float[] samples) {

        // move the pixel array down
        System.arraycopy(pixels,0,pixels,WIDTH,(WIDTH*(HEIGHT-1)));

        // draw the new line
        for(int i=0;i<WIDTH;i++) {
            pixels[i]=calculatePixel(samples[i]);
        }

        this.repaint();
    }

    private int calculatePixel(float sample) {
        // simple gray scale
        int v=((int)sample-low)*255/(high-low);

        if(v<0) v=0;
        if(v>255) v=255;

        int pixel=(255<<24)+(v<<16)+(v<<8)+v;
        return pixel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(480, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private static final int WIDTH=480;
    private static final int HEIGHT=100;

    private int low=-120;
    private int high=-60;

    private int pixels[];


}
