// -------------------------------------------------------------
//
// Module: filter
//
// Generated by MATLAB(R) 7.2 and the Filter Design HDL Coder 1.4.
//
// Generated on: 2006-06-12 11:17:59
//
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetLanguage: Verilog
// TargetDirectory: C:\DOCUME~1\phil\LOCALS~1\Temp\tp165358\hdlsrc
// SerialPartition: -1
// CastBeforeSum: On
//
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure        : Cascaded Integrator-Comb Decimator
// Decimation Factor       : 2048
// Differential Delay      : 1
// Number of Sections      : 3
// Stable                  : Yes
// Linear Phase            : Yes (Type 2)
//
// Input                   : s16,15
// Output                  : s16,-18
// Filter Internals        : Minimum Word Lengths
//   Integrator Section 1  : s45,11
//   Integrator Section 2  : s34,0
//   Integrator Section 3  : s25,-9
//   Comb Section 1        : s20,-14
//   Comb Section 2        : s19,-15
//   Comb Section 3        : s18,-16
//
// Implementation Cost
// Number of Multipliers : 0
// Number of Adders      : 6
// Number of States      : 6
// MultPerInputSample    : 0
// AddPerInputSample     : 3.0015
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module filter 
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_E18
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  // Signals
  reg  [10:0] cur_count; // ufix11
  wire phase_1; // boolean
  reg  ce_out_reg; // boolean
  //   
  reg  signed [15:0] input_register; // sfix16_En15
  //   -- Section 1 Signals 
  wire signed [15:0] section_in1; // sfix16_En15
  wire signed [44:0] section_cast1; // sfix45_En11
  wire signed [44:0] sum1; // sfix45_En11
  reg  signed [44:0] section_out1; // sfix45_En11
  wire signed [44:0] add_cast; // sfix45_En11
  wire signed [44:0] add_cast_1; // sfix45_En11
  wire signed [45:0] add_temp; // sfix46_En11
  //   -- Section 2 Signals 
  wire signed [44:0] section_in2; // sfix45_En11
  wire signed [33:0] section_cast2; // sfix34
  wire signed [33:0] sum2; // sfix34
  reg  signed [33:0] section_out2; // sfix34
  wire signed [33:0] add_cast_2; // sfix34
  wire signed [33:0] add_cast_3; // sfix34
  wire signed [34:0] add_temp_1; // sfix35
  //   -- Section 3 Signals 
  wire signed [33:0] section_in3; // sfix34
  wire signed [24:0] section_cast3; // sfix25_E9
  wire signed [24:0] sum3; // sfix25_E9
  reg  signed [24:0] section_out3; // sfix25_E9
  wire signed [24:0] add_cast_4; // sfix25_E9
  wire signed [24:0] add_cast_5; // sfix25_E9
  wire signed [25:0] add_temp_2; // sfix26_E9
  //   -- Section 4 Signals 
  wire signed [24:0] section_in4; // sfix25_E9
  wire signed [19:0] section_cast4; // sfix20_E14
  reg  signed [19:0] diff1; // sfix20_E14
  wire signed [19:0] section_out4; // sfix20_E14
  wire signed [19:0] sub_cast; // sfix20_E14
  wire signed [19:0] sub_cast_1; // sfix20_E14
  wire signed [20:0] sub_temp; // sfix21_E14
  //   -- Section 5 Signals 
  wire signed [19:0] section_in5; // sfix20_E14
  wire signed [18:0] section_cast5; // sfix19_E15
  reg  signed [18:0] diff2; // sfix19_E15
  wire signed [18:0] section_out5; // sfix19_E15
  wire signed [18:0] sub_cast_2; // sfix19_E15
  wire signed [18:0] sub_cast_3; // sfix19_E15
  wire signed [19:0] sub_temp_1; // sfix20_E15
  //   -- Section 6 Signals 
  wire signed [18:0] section_in6; // sfix19_E15
  wire signed [17:0] section_cast6; // sfix18_E16
  reg  signed [17:0] diff3; // sfix18_E16
  wire signed [17:0] section_out6; // sfix18_E16
  wire signed [17:0] sub_cast_4; // sfix18_E16
  wire signed [17:0] sub_cast_5; // sfix18_E16
  wire signed [18:0] sub_temp_2; // sfix19_E16
  wire signed [15:0] output_typeconvert; // sfix16_E18
  //   
  reg  signed [15:0] output_register; // sfix16_E18

  // Block Statements
  //   ------------------ CE Output Generation ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 11'b00000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count == 11'b11111111111) begin
            cur_count <= 11'b00000000000;
          end
          else begin
            cur_count <= cur_count + 1;
          end
        end
      end
    end // ce_output

  assign  phase_1 = (cur_count == 11'b00000000001 && clk_enable == 1'b1)? 1 : 0;

  //   ------------------ CE Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output_register
      if (reset == 1'b1) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= phase_1;
      end
    end // ce_output_register

  //   ------------------ Input Register ------------------

  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  //   ------------------ Section # 1 : Integrator ------------------

  assign section_in1 = input_register;

  assign section_cast1 = $signed({{33{section_in1[15]}}, section_in1[15:4]});

  assign add_cast = section_cast1;
  assign add_cast_1 = section_out1;
  assign add_temp = add_cast + add_cast_1;
  assign sum1 = add_temp[44:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section1
      if (reset == 1'b1) begin
        section_out1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out1 <= sum1;
        end
      end
    end // integrator_delay_section1

  //   ------------------ Section # 2 : Integrator ------------------

  assign section_in2 = section_out1;

  assign section_cast2 = section_in2[44:11];

  assign add_cast_2 = section_cast2;
  assign add_cast_3 = section_out2;
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign sum2 = add_temp_1[33:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section2
      if (reset == 1'b1) begin
        section_out2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out2 <= sum2;
        end
      end
    end // integrator_delay_section2

  //   ------------------ Section # 3 : Integrator ------------------

  assign section_in3 = section_out2;

  assign section_cast3 = section_in3[33:9];

  assign add_cast_4 = section_cast3;
  assign add_cast_5 = section_out3;
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign sum3 = add_temp_2[24:0];

  always @ (posedge clk or posedge reset)
    begin: integrator_delay_section3
      if (reset == 1'b1) begin
        section_out3 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out3 <= sum3;
        end
      end
    end // integrator_delay_section3

  //   ------------------ Section # 4 : Comb ------------------

  assign section_in4 = section_out3;

  assign section_cast4 = section_in4[24:5];

  assign sub_cast = section_cast4;
  assign sub_cast_1 = diff1;
  assign sub_temp = sub_cast - sub_cast_1;
  assign section_out4 = sub_temp[19:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section4
      if (reset == 1'b1) begin
        diff1 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff1 <= section_cast4;
        end
      end
    end // comb_delay_section4

  //   ------------------ Section # 5 : Comb ------------------

  assign section_in5 = section_out4;

  assign section_cast5 = section_in5[19:1];

  assign sub_cast_2 = section_cast5;
  assign sub_cast_3 = diff2;
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign section_out5 = sub_temp_1[18:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section5
      if (reset == 1'b1) begin
        diff2 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff2 <= section_cast5;
        end
      end
    end // comb_delay_section5

  //   ------------------ Section # 6 : Comb ------------------

  assign section_in6 = section_out5;

  assign section_cast6 = section_in6[18:1];

  assign sub_cast_4 = section_cast6;
  assign sub_cast_5 = diff3;
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign section_out6 = sub_temp_2[17:0];

  always @ (posedge clk or posedge reset)
    begin: comb_delay_section6
      if (reset == 1'b1) begin
        diff3 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff3 <= section_cast6;
        end
      end
    end // comb_delay_section6

  assign output_typeconvert = section_out6[17:2];

  //   ------------------ Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: output_reg_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // output_reg_process

  // Assignment Statements
  assign ce_out = ce_out_reg;
  assign filter_out = output_register;
endmodule  // filter
