/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.g0orx.openhpsdr;

import org.g0orx.openhpsdr.discovery.Discovered;

/**
 *
 * @author john
 */
public class BandscopeJDialog extends javax.swing.JDialog {

    /**
     * Creates new form BandscopeJDialog
     */
    public BandscopeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setVisible(true);
        Discovered selected=Configuration.getInstance().discovered;
        this.setTitle("openHPSDR Bandscope: " + selected.getDeviceName() + " " + selected.getAddress() + " (" + selected.getMac() + ")");
    }
    
    public void update(float[] samples) {
        this.bandscopePanel1.update(samples);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bandscopePanel1 = new org.g0orx.openhpsdr.BandscopePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout bandscopePanel1Layout = new javax.swing.GroupLayout(bandscopePanel1);
        bandscopePanel1.setLayout(bandscopePanel1Layout);
        bandscopePanel1Layout.setHorizontalGroup(
            bandscopePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        bandscopePanel1Layout.setVerticalGroup(
            bandscopePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bandscopePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bandscopePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.g0orx.openhpsdr.BandscopePanel bandscopePanel1;
    // End of variables declaration//GEN-END:variables
}
