/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.g0orx.openhpsdr;

/**
 *
 * @author john
 */
public class ModePanel extends javax.swing.JPanel {

    /**
     * Creates new form Mode
     */
    public ModePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLSB = new javax.swing.JButton();
        jButtonUSB = new javax.swing.JButton();
        jButtonDSB = new javax.swing.JButton();
        jButtonCWL = new javax.swing.JButton();
        jButtonCWU = new javax.swing.JButton();
        jButtonFMN = new javax.swing.JButton();
        jButtonAM = new javax.swing.JButton();
        jButtonDIGU = new javax.swing.JButton();
        jButtonSPEC = new javax.swing.JButton();
        jButtonDIGL = new javax.swing.JButton();
        jButtonSAM = new javax.swing.JButton();
        jButtonDRM = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 3));

        jButtonLSB.setText("LSB");
        jButtonLSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLSBActionPerformed(evt);
            }
        });
        add(jButtonLSB);

        jButtonUSB.setText("USB");
        jButtonUSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUSBActionPerformed(evt);
            }
        });
        add(jButtonUSB);

        jButtonDSB.setText("DSB");
        jButtonDSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDSBActionPerformed(evt);
            }
        });
        add(jButtonDSB);

        jButtonCWL.setText("CWL");
        jButtonCWL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCWLActionPerformed(evt);
            }
        });
        add(jButtonCWL);

        jButtonCWU.setText("CWU");
        jButtonCWU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCWUActionPerformed(evt);
            }
        });
        add(jButtonCWU);

        jButtonFMN.setText("FMN");
        jButtonFMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFMNActionPerformed(evt);
            }
        });
        add(jButtonFMN);

        jButtonAM.setText("AM");
        jButtonAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAMActionPerformed(evt);
            }
        });
        add(jButtonAM);

        jButtonDIGU.setText("DIGU");
        jButtonDIGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDIGUActionPerformed(evt);
            }
        });
        add(jButtonDIGU);

        jButtonSPEC.setText("SPEC");
        jButtonSPEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSPECActionPerformed(evt);
            }
        });
        add(jButtonSPEC);

        jButtonDIGL.setText("DIGL");
        jButtonDIGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDIGLActionPerformed(evt);
            }
        });
        add(jButtonDIGL);

        jButtonSAM.setText("SAM");
        jButtonSAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAMActionPerformed(evt);
            }
        });
        add(jButtonSAM);

        jButtonDRM.setText("DRM");
        jButtonDRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDRMActionPerformed(evt);
            }
        });
        add(jButtonDRM);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCWLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCWLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCWLActionPerformed

    private void jButtonLSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLSBActionPerformed

    private void jButtonUSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUSBActionPerformed

    private void jButtonDSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDSBActionPerformed

    private void jButtonCWUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCWUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCWUActionPerformed

    private void jButtonFMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFMNActionPerformed

    private void jButtonAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAMActionPerformed

    private void jButtonDIGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDIGUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDIGUActionPerformed

    private void jButtonSPECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSPECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSPECActionPerformed

    private void jButtonDIGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDIGLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDIGLActionPerformed

    private void jButtonSAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSAMActionPerformed

    private void jButtonDRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDRMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAM;
    private javax.swing.JButton jButtonCWL;
    private javax.swing.JButton jButtonCWU;
    private javax.swing.JButton jButtonDIGL;
    private javax.swing.JButton jButtonDIGU;
    private javax.swing.JButton jButtonDRM;
    private javax.swing.JButton jButtonDSB;
    private javax.swing.JButton jButtonFMN;
    private javax.swing.JButton jButtonLSB;
    private javax.swing.JButton jButtonSAM;
    private javax.swing.JButton jButtonSPEC;
    private javax.swing.JButton jButtonUSB;
    // End of variables declaration//GEN-END:variables
}
