/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.g0orx.openhpsdr;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.g0orx.openhpsdr.wdsp.WDSP;

/**
 *
 * @author john
 */
public class RadioJDialog extends javax.swing.JDialog {

    /**
     * Creates new form RadioJDialog
     */
    public RadioJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configuration = Configuration.getInstance();
        wdsp = WDSP.getInstance();
        this.jCheckBoxNB2Enable.setSelected(configuration.NB2);
        this.jCheckBoxAEFilter.setSelected(configuration.NB2_AE);
        this.jRadioButtonLinear.setSelected(configuration.NB2_GAIN == 0);
        this.jRadioButtonLog.setSelected(configuration.NB2_GAIN == 1);
        this.jRadioButtonOSMS.setSelected(configuration.NB2_NPE == 0);
        this.jRadioButtonMMSE.setSelected(configuration.NB2_NPE == 1);
        this.jRadioButtonPreAGC.setSelected(configuration.NB2_POSITION == 0);
        this.jRadioButtonPostAGC.setSelected(configuration.NB2_POSITION == 1);
        this.jCheckBoxNR.setSelected(configuration.NR);
        this.jCheckBoxANF.setSelected(configuration.ANF);
        this.jSliderAttenuation.setMinimum(0);
        this.jSliderAttenuation.setMaximum(61);
        this.jSliderAttenuation.setValue(configuration.attenuation);
        this.jSliderAttenuation.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                javax.swing.JSlider source = (javax.swing.JSlider) e.getSource();
                configuration.attenuation = (int) source.getValue();
                jLabelAttenuation.setText("Attenuation: "+configuration.attenuation+"dB");
            }
        });
        this.jLabelAttenuation.setText("Attenuation: "+configuration.attenuation+"dB");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGain = new javax.swing.ButtonGroup();
        buttonGroupNPEMethod = new javax.swing.ButtonGroup();
        buttonGroupPosition = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxNB2Enable = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonLinear = new javax.swing.JRadioButton();
        jRadioButtonLog = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonOSMS = new javax.swing.JRadioButton();
        jRadioButtonMMSE = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonPreAGC = new javax.swing.JRadioButton();
        jRadioButtonPostAGC = new javax.swing.JRadioButton();
        jCheckBoxAEFilter = new javax.swing.JCheckBox();
        jCheckBoxNR = new javax.swing.JCheckBox();
        jCheckBoxANF = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabelAttenuation = new javax.swing.JLabel();
        jSliderAttenuation = new javax.swing.JSlider();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCheckBoxNB2Enable.setText("NB2");
        jCheckBoxNB2Enable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNB2EnableActionPerformed(evt);
            }
        });

        jLabel1.setText("Gain Method:");

        buttonGroupGain.add(jRadioButtonLinear);
        jRadioButtonLinear.setText("Linear");
        jRadioButtonLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLinearActionPerformed(evt);
            }
        });

        buttonGroupGain.add(jRadioButtonLog);
        jRadioButtonLog.setText("Log");
        jRadioButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLogActionPerformed(evt);
            }
        });

        jLabel2.setText("NPE Method:");

        buttonGroupNPEMethod.add(jRadioButtonOSMS);
        jRadioButtonOSMS.setText("OSMS");
        jRadioButtonOSMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOSMSActionPerformed(evt);
            }
        });

        buttonGroupNPEMethod.add(jRadioButtonMMSE);
        jRadioButtonMMSE.setText("MMSE");
        jRadioButtonMMSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMMSEActionPerformed(evt);
            }
        });

        jLabel3.setText("Position:");

        buttonGroupPosition.add(jRadioButtonPreAGC);
        jRadioButtonPreAGC.setText("Pre AGC");
        jRadioButtonPreAGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPreAGCActionPerformed(evt);
            }
        });

        buttonGroupPosition.add(jRadioButtonPostAGC);
        jRadioButtonPostAGC.setText("Post AGC");
        jRadioButtonPostAGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPostAGCActionPerformed(evt);
            }
        });

        jCheckBoxAEFilter.setText("AE Filter");
        jCheckBoxAEFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAEFilterActionPerformed(evt);
            }
        });

        jCheckBoxNR.setText("NR");
        jCheckBoxNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNRActionPerformed(evt);
            }
        });

        jCheckBoxANF.setText("ANF");
        jCheckBoxANF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxANFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxNB2Enable)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonPreAGC)
                                            .addComponent(jLabel3))
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBoxAEFilter)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonLinear)
                                    .addComponent(jRadioButtonLog))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonMMSE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonPostAGC)
                                        .addContainerGap())
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonOSMS)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxNR)
                            .addComponent(jCheckBoxANF))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxNB2Enable)
                    .addComponent(jCheckBoxAEFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOSMS)
                    .addComponent(jRadioButtonPreAGC)
                    .addComponent(jRadioButtonLinear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMMSE)
                    .addComponent(jRadioButtonPostAGC)
                    .addComponent(jRadioButtonLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxNR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxANF)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DSP", jPanel1);

        jLabelAttenuation.setText("Attenuation:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSliderAttenuation, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAttenuation, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelAttenuation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderAttenuation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gain", jPanel2);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jButtonClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jRadioButtonOSMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOSMSActionPerformed
        configuration.NB2_NPE = 0;
        wdsp.SetRXAEMNRnpeMethod(Channel.RX, 0);
    }//GEN-LAST:event_jRadioButtonOSMSActionPerformed

    private void jCheckBoxNB2EnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNB2EnableActionPerformed
        configuration.NB2 = this.jCheckBoxNB2Enable.isSelected();
        wdsp.SetRXAEMNRRun(Channel.RX, configuration.NB2 ? 1 : 0);
    }//GEN-LAST:event_jCheckBoxNB2EnableActionPerformed

    private void jCheckBoxAEFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAEFilterActionPerformed
        configuration.NB2_AE = this.jCheckBoxAEFilter.isSelected();
        wdsp.SetRXAEMNRaeRun(Channel.RX, configuration.NB2_AE ? 1 : 0);
    }//GEN-LAST:event_jCheckBoxAEFilterActionPerformed

    private void jRadioButtonLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLinearActionPerformed
        configuration.NB2_GAIN = 0;
        wdsp.SetRXAEMNRgainMethod(Channel.RX, 0);
    }//GEN-LAST:event_jRadioButtonLinearActionPerformed

    private void jRadioButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLogActionPerformed
        configuration.NB2_GAIN = 1;
        wdsp.SetRXAEMNRgainMethod(Channel.RX, 1);
    }//GEN-LAST:event_jRadioButtonLogActionPerformed

    private void jRadioButtonMMSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMMSEActionPerformed
        configuration.NB2_NPE = 1;
        wdsp.SetRXAEMNRnpeMethod(Channel.RX, 1);
    }//GEN-LAST:event_jRadioButtonMMSEActionPerformed

    private void jRadioButtonPreAGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPreAGCActionPerformed
        configuration.NB2_POSITION = 0;
        wdsp.SetRXAEMNRPosition(Channel.RX, 0);
    }//GEN-LAST:event_jRadioButtonPreAGCActionPerformed

    private void jRadioButtonPostAGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPostAGCActionPerformed
        configuration.NB2_POSITION = 1;
        wdsp.SetRXAEMNRPosition(Channel.RX, 1);
    }//GEN-LAST:event_jRadioButtonPostAGCActionPerformed

    private void jCheckBoxNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNRActionPerformed
        configuration.NR = this.jCheckBoxNR.isSelected();
        wdsp.SetRXAANRRun(Channel.RX, configuration.NR ? 1 : 0);
    }//GEN-LAST:event_jCheckBoxNRActionPerformed

    private void jCheckBoxANFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxANFActionPerformed
        configuration.ANF = this.jCheckBoxANF.isSelected();
        wdsp.SetRXAANFRun(Channel.RX, configuration.ANF ? 1 : 0);
    }//GEN-LAST:event_jCheckBoxANFActionPerformed

    private Configuration configuration;
    private WDSP wdsp;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGain;
    private javax.swing.ButtonGroup buttonGroupNPEMethod;
    private javax.swing.ButtonGroup buttonGroupPosition;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JCheckBox jCheckBoxAEFilter;
    private javax.swing.JCheckBox jCheckBoxANF;
    private javax.swing.JCheckBox jCheckBoxNB2Enable;
    private javax.swing.JCheckBox jCheckBoxNR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAttenuation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonLinear;
    private javax.swing.JRadioButton jRadioButtonLog;
    private javax.swing.JRadioButton jRadioButtonMMSE;
    private javax.swing.JRadioButton jRadioButtonOSMS;
    private javax.swing.JRadioButton jRadioButtonPostAGC;
    private javax.swing.JRadioButton jRadioButtonPreAGC;
    private javax.swing.JSlider jSliderAttenuation;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
