#ifndef TIMEOUTS_H
#define TIMEOUTS_H

#define BOARD_DISCOVERY_TIMEOUT  4000  // 4 seconds
#define METIS_MAX_ERASE_TIMEOUTS 20000 // 20 seconds
#define HERMES_MAX_ERASE_TIMEOUTS 40000 // 40 seconds
#define ANGELIA_MAX_ERASE_TIMEOUTS 90000 // 90 seconds

#endif // TIMEOUTS_H
